version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation with Mkdocs
mkdocs:
   configuration: mkdocs.yml

# Dependencies required to build your docs
python:
   install:
   - requirements: requirements/docs.txt