services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: classlab_local_django
    container_name: classlab_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
      - ./kubeconfig:/kube/config
    environment:
      - USE_DOCKER=yes
      - PYTHONDEVMODE=1
      - IPYTHONDIR=/app/.ipython
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_FLOWER_USER=debug
      - CELERY_FLOWER_PASSWORD=debug
      - CONTACT_EMAIL=kontakt@classlab.pl
      - K8S_HOST=ur
      - K8S_TOKEN=token
      - K8S_CA_CERT=cert
      - PROXY_DOMAIN=apps.classlab.localhost
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/classlab
      - KUBECONFIG=/kube/config
      - PROMETHEUS_URL=http://host.docker.internal:9090
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:15
    container_name: classlab_local_postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=classlab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: classlab_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: classlab_local_redis

  celeryworker:
    <<: *django
    image: classlab_local_celeryworker
    container_name: classlab_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: classlab_local_celerybeat
    container_name: classlab_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: classlab_local_flower
    container_name: classlab_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
