repositories:
  - name: kedacore
    url: https://kedacore.github.io/charts

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: keda
    namespace: keda
    chart: kedacore/keda
    createNamespace: true

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    createNamespace: true
    disableValidationOnInstall: true
    values:
      - ./infra/k8s-dev/kube-prometheus/values.yml
