---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: technr2
  name: vscode
  labels:
    app: vscode
    user: jankow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode
      user: jankow
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vscode
        user: jankow
    spec:
      containers:
        - name: code-server
          image: lscr.io/linuxserver/code-server:latest
          ports:
            - containerPort: 8443
              name: code-server

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Warsaw"
            - name: PASSWORD
              value: "password"
            - name: SUDO_PASSWORD
              value: "password"
            - name: PROXY_DOMAIN
              value: "vscode.apps.classlab.test"
            - name: DEFAULT_WORKSPACE
              value: "/workspace"

          volumeMounts:
            - name: data
              mountPath: /workspace

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vscode

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: technr2
  name: vscode
  labels:
    app: vscode
    user: jankow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  namespace: technr2
  name: vscode
  labels:
    app: vscode
    user: jankow
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8443
  selector:
    app: vscode
    user: jankow

# ---
# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: vscode
#   namespace: technr2
# spec:
#   scaleTargetRef:
#     name: vscode
#   pollingInterval: 15
#   cooldownPeriod: 600
#   minReplicaCount: 0
#   maxReplicaCount: 1
#   advanced:
#     horizontalPodAutoscalerConfig:
#       behavior:
#         scaleDown:
#           stabilizationWindowSeconds: 600
#           policies:
#           - type: Percent
#             value: 100
#             periodSeconds: 15
#         scaleUp:
#           selectPolicy: Disabled
#   triggers:
#     - type: prometheus
#       metricType: Value
#       metadata:
#         serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
#         query: max(max(sum(rate(container_fs_reads_total{container!="",job="kubelet",metrics_path="/metrics/cadvisor",pod=~"vscode.*"}[2m30s])+rate(container_fs_writes_total{container!="",job="kubelet",metrics_path="/metrics/cadvisor",pod=~"vscode.*"}[2m30s]))) * 100 > bool 10 or (time() - kube_pod_created{pod=~"vscode.*", namespace="technr2"} < bool 300))
#         threshold: "1"
#         ignoreNullValues: "false"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vscode
  namespace: technr2
spec:
  ingressClassName: nginx
  rules:
  - host: vscode.apps.classlab.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vscode
            port:
              number: 80