# Generated by Django 4.0.10 on 2023-04-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('namespace', models.CharField(max_length=255, verbose_name='Namespace')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_config', to='organisations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Cluster Config',
                'verbose_name_plural': 'Cluster Configs',
            },
        ),
    ]
