# Generated by Django 4.2 on 2023-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterconfig",
            name="nodepool",
            field=models.CharField(default="", max_length=255, verbose_name="Nodepool"),
            preserve_default=False,
        ),
    ]
