# Generated by Django 4.2 on 2023-06-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0001_initial"),
        ("cloud", "0002_clusterconfig_nodepool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clusterconfig",
            name="nodepool",
        ),
        migrations.AddField(
            model_name="clusterconfig",
            name="spot_pool",
            field=models.BooleanField(default=True, verbose_name="Spot Pool"),
        ),
        migrations.CreateModel(
            name="ResourceQuota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cpu", models.IntegerField(verbose_name="CPU")),
                ("memory", models.IntegerField(verbose_name="Memory")),
                ("storage", models.IntegerField(verbose_name="Storage")),
                (
                    "orgnisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_quota",
                        to="organisations.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Quota",
                "verbose_name_plural": "Resource Quotas",
            },
        ),
    ]
