# Generated by Django 4.2 on 2023-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0003_remove_clusterconfig_nodepool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcequota",
            name="cpu",
            field=models.IntegerField(help_text="CPU in millicores", verbose_name="CPU"),
        ),
        migrations.AlterField(
            model_name="resourcequota",
            name="memory",
            field=models.IntegerField(help_text="Memory in MiB", verbose_name="Memory"),
        ),
        migrations.AlterField(
            model_name="resourcequota",
            name="storage",
            field=models.IntegerField(help_text="Storage in GiB", verbose_name="Storage"),
        ),
    ]
