# Generated by Django 4.2 on 2023-06-19 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrators", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrator",
            options={
                "permissions": [("view_dashboard", "Can view dashboard")],
                "verbose_name": "Administrator",
                "verbose_name_plural": "Administrators",
            },
        ),
    ]
