# Generated by Django 4.1.8 on 2023-05-03 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "permissions": [
                    (
                        "student_resend_confirm_email",
                        "Can resend confirmation email to student",
                    )
                ],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
    ]
