# Generated by Django 4.1.8 on 2023-05-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("ADMIN", "Organization Administrator"),
                ],
                max_length=7,
                null=True,
                verbose_name="user type",
            ),
        ),
    ]
