#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py set_permissions
python /app/manage.py compilemessages
python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
