# Generated by Django 4.0.10 on 2023-04-16 17:58

import classlab.utils.generator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'App Category',
                'verbose_name_plural': 'App Categories',
            },
        ),
        migrations.CreateModel(
            name='AppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(default=classlab.utils.generator.generate_random_id, editable=False, max_length=12, unique=True, verbose_name='Template ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('manifest', models.TextField(verbose_name='Manifest')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_templates', to='apps.appcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'App Template',
                'verbose_name_plural': 'App Templates',
            },
        ),
        migrations.CreateModel(
            name='AppTemplateKeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('key', models.CharField(max_length=100, verbose_name='Key')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Value')),
                ('type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean')], default='string', max_length=10, verbose_name='Type')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('secret', models.BooleanField(default=False, verbose_name='Secret')),
                ('end_user_editable', models.BooleanField(default=False, verbose_name='End User Editable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('app_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_values', to='apps.apptemplate', verbose_name='App Template')),
            ],
            options={
                'verbose_name': 'App Template Key Value',
                'verbose_name_plural': 'App Template Key Values',
                'unique_together': {('app_template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default=classlab.utils.generator.generate_random_id, editable=False, max_length=12, unique=True, verbose_name='App ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_apps', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', related_query_name='app', to='organisations.organisation', verbose_name='Organisation')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='apps.apptemplate', verbose_name='Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', related_query_name='app', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
