# Generated by Django 4.0.10 on 2023-04-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'permissions': [('start_app', 'Can start an app'), ('stop_app', 'Can stop an app')], 'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
    ]
