# Generated by Django 4.1.8 on 2023-05-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_apptemplate_expose_node_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apptemplatekeyvalue",
            name="generated",
            field=models.BooleanField(default=False, verbose_name="Generated"),
        ),
    ]
