# Generated by Django 4.1.8 on 2023-05-24 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_apptemplatekeyvalue_generated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apptemplatekeyvalue",
            name="value",
        ),
    ]
