# Generated by Django 4.1.8 on 2023-05-31 18:07

import classlab.utils.generator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0001_initial"),
        ("apps", "0005_remove_apptemplatekeyvalue_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="apptemplate",
            name="managed",
            field=models.BooleanField(default=False, verbose_name="Managed"),
        ),
        migrations.AddField(
            model_name="apptemplatekeyvalue",
            name="generator",
            field=models.CharField(
                blank=True,
                choices=[("password", "Password"), ("username", "Username")],
                max_length=10,
                null=True,
                verbose_name="Generator",
            ),
        ),
        migrations.AddField(
            model_name="apptemplatekeyvalue",
            name="student_only",
            field=models.BooleanField(default=False, verbose_name="Student Only"),
        ),
        migrations.AddField(
            model_name="apptemplatekeyvalue",
            name="teacher_only",
            field=models.BooleanField(default=False, verbose_name="Teacher Only"),
        ),
        migrations.AlterUniqueTogether(
            name="apptemplate",
            unique_together={("name", "template_id")},
        ),
        migrations.CreateModel(
            name="ManagedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "managed_app_id",
                    models.CharField(
                        default=classlab.utils.generator.generate_random_id,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="Managed App ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "assigned_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_apps",
                        related_query_name="managed_app",
                        to="classes.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_managed_apps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_apps",
                        related_query_name="managed_app",
                        to="organisations.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_apps",
                        to="apps.apptemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed App",
                "verbose_name_plural": "Managed Apps",
                "unique_together": {("assigned_class", "name")},
            },
        ),
        migrations.AddField(
            model_name="app",
            name="managed_app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apps",
                to="apps.managedapp",
                verbose_name="Managed App",
            ),
        ),
    ]
