# Generated by Django 4.1.8 on 2023-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0001_initial"),
        ("apps", "0006_apptemplate_managed_apptemplatekeyvalue_generator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apptemplate",
            name="organisations",
            field=models.ManyToManyField(
                related_name="app_templates",
                related_query_name="app_template",
                to="organisations.organisation",
                verbose_name="Organisations",
            ),
        ),
    ]
