# Generated by Django 4.0.10 on 2023-04-16 17:58

import classlab.utils.generator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_id', models.CharField(default=classlab.utils.generator.generate_random_id, editable=False, max_length=12, unique=True, verbose_name='Organisation ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_organisations', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='OrganisationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_number_of_students', models.PositiveIntegerField(default=0, verbose_name='Max number of students')),
                ('max_number_of_teachers', models.PositiveIntegerField(default=0, verbose_name='Max number of teachers')),
                ('max_number_of_apps_per_student', models.PositiveIntegerField(default=0, verbose_name='Max number of apps per student')),
                ('max_number_of_apps_per_teacher', models.PositiveIntegerField(default=0, verbose_name='Max number of apps per teacher')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='organisations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Organisation Quota',
                'verbose_name_plural': 'Organisation Quotas',
            },
        ),
    ]
